CREATE TABLE IF NOT EXISTS MOTORISTAS(
   id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   nome VARCHAR(100) NOT NULL,
   cpf CHAR(11) UNIQUE NOT NULL,
   placa_veiculo VARCHAR(15) UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS ENTREGAS(
   id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   descricao VARCHAR(255) NOT NULL,
   origem VARCHAR(255) NOT NULL,
   destino VARCHAR(255) NOT NULL,
   status VARCHAR(15) NOT NULL CHECK(status IN ('CRIADA', 'EM_TRANSITO', 'ENTREGUE', 'CANCELADA')),
   motorista_id INTEGER,
   CONSTRAINT motorista_id_fk FOREIGN KEY (motorista_id) REFERENCES MOTORISTAS(id)
);
CREATE TABLE IF NOT EXISTS EVENTOS_ENTREGA(
   id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   data_evento TIMESTAMP NOT NULL DEFAULT now(),
   descricao VARCHAR(255) NOT NULL,
   entrega_id INTEGER  NOT NULL,
   CONSTRAINT entrega_id_fk FOREIGN KEY (entrega_id) REFERENCES ENTREGAS(id) ON DELETE CASCADE
);

ALTER TABLE IF EXISTS MOTORISTAS ADD COLUMN IF NOT EXISTS status VARCHAR(15) NOT NULL CHECK(status IN ('ATIVO', 'INATIVO')) DEFAULT 'ATIVO'
